### ISSUE TITLE
Error: "Failed to find the ask-resources.json"

### ISSUE THREAD

**Issue by snadeau89** [andrei-ace/music-cloud#5]
Hi!

I'm quite a newbie, but, with a lot of patience, I managed to create this music skill. Unfortunately, I don't seem to be able to deploy it, no matter what I try... Here is the error I get every time I try the "ask deploy" command:

`[Warn]: Failed to find the ask-resources.json file to deploy with from the current directory.`

And on this screenshot, you can see from which directory I try this command.
![Annotation 2020-09-01 044326](https://user-images.githubusercontent.com/68289537/91828514-3b7d8300-ec0e-11ea-9bcf-44b3da83d043.png)

Could you please help me with this? I have no idea what I'm doing wrong...

**Comment by andrei-ace** [comment]
Did you run ask-cli init?

**Comment by andrei-ace** [comment]
The medium article has many manual steps. The instructions from github are for a more automated process.

**Comment by snadeau89** [comment]
Hi Andrei! Yes, I did!

I moved some files to my music-cloud directory, which solved this issue.

Unfortunately, I'm now encountering a new issue:

`[Error]: CliError: The skillMetadata src file ./music-cloud/lambda/us-east-1_MusicCloudLambda/ does not exist.`

Here is the screenshots of my directory:
![Annotation 2020-09-01 051725](https://user-images.githubusercontent.com/68289537/91831810-84373b00-ec12-11ea-976c-ea8df9072290.png)
![Annotation 2020-09-01 051750](https://user-images.githubusercontent.com/68289537/91831812-84373b00-ec12-11ea-9815-862c4fe689b4.png)

(By the way, if you want me to rewrite the instructions more in details, I would be happy to do so. I'm a copywriter.)

**Comment by andrei-ace** [comment]
Try to run the commands one directory higher (in the "Git" directory, not in music-cloud).
I would be glad to get help from you with the description. Please create a pull request.

**Comment by andrei-ace** [comment]
To be honest I did not try it on a windows machine, that might be the source of the problems.

**Comment by andrei-ace** [comment]
The file structure should be the exact one from github.

**Comment by snadeau89** [comment]
I will create a pull request as soon as I will have managed to deploy the skill. :)

**Comment by snadeau89** [comment]
Is there any other way to deploy?

**Comment by andrei-ace** [comment]
Using the manual steps described in the medium article.

**Comment by snadeau89** [comment]
This article https://medium.com/voice-tech-podcast/build-your-own-music-streaming-service-with-amazon-alexa-41c7bf1eb66a ?

The steps for deployment are with ASK CLI in this article...

**Comment by andrei-ace** [comment]
You should be able to create everything from UI. Maybe this article will help you https://medium.com/crowdbotics/how-to-build-a-custom-amazon-alexa-skill-step-by-step-my-favorite-chess-player-dcc0edae53fb

**Comment by andrei-ace** [comment]
You might be able to make the scripts to work on windows with WSL:
https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by snadeau89** [comment]
Okay! Trying right now!

**Comment by snadeau89** [comment]
The problem with the Alexa Developer Console is there is no code section available for music skills... Hopefully I'll be able to deploy with Linux subsystem!

**Comment by andrei-ace** [comment]
You can deploy the code using the AWS UI: https://docs.aws.amazon.com/lambda/latest/dg/getting-started-create-function.html but it is error prone and labour intensive to create all those by hand. By the way, you'll need to create an AWS account where to deploy the lambda function.

**Comment by snadeau89** [comment]
Yeah, I tried that method at first, but since I'm no expert, I didn't know where I should save/copy the skill.json file...
